export {
  type SegmentId,
  type InterviewPhase,
  type ProblemFields,
  type ProductReactionFields,
  type CustomerEvidenceRecord,
  type IcpAmendmentProposal,
  FORBIDDEN_INTERVIEW_QUESTIONS,
  CORE_PROBLEM_QUESTIONS,
  EVIDENCE_DB,
  assertNoForbiddenQuestion,
  assertCoreQuestionsAreBehavioral,
  assertProblemFieldsPresent,
  addEvidenceRecord,
  canProposeIcpAmendment,
  countBySegment,
  evidenceSummary,
} from "./store";
